name = "anju-mcp"
main = "dist/index.js"
compatibility_date = "2025-11-17"

compatibility_flags = ["nodejs_compat", "nodejs_compat_populate_process_env"]

[observability]
enabled = true

[build]
command = "npm run build"

[env.development]
name = "anju-mcp-development"
[env.development.vars]
NODE_ENV = "production"
[[env.development.hyperdrive]]
binding = "HYPERDRIVE"
id = "20b38b96e12a4f45ac111fb7d8161edf"

[env.production]
name = "anju-mcp-production"
[env.production.vars]
NODE_ENV = "production"
[[env.production.hyperdrive]]
binding = "HYPERDRIVE"
id = "<YOUR_HYPERDRIVE_ID>"
