name = "anju"
main = "dist/index.js"
compatibility_date = "2025-04-01"

compatibility_flags = ["nodejs_compat", "nodejs_compat_populate_process_env"]

[build]
command = "npm run build"

[env.development]
name = "anju-development"
[env.development.vars]
NODE_ENV = "development"
NEXT_PUBLIC_API_URL="http://localhost:8080"
NEXT_PUBLIC_WEB_URL="http://localhost:3000"

[env.production]
name = "anju-production"
[env.production.vars]
NODE_ENV = "production"
NEXT_PUBLIC_API_URL="https://api.anju.ai"
NEXT_PUBLIC_WEB_URL="https://app.anju.ai"
